app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::post('cambiar-idioma',['uses'=>'GeneralController@changeLanguage']);

Route::get('/perfil/login',['uses'	=> 'Perfil\UserController@login']);
Route::group(['prefix' => 'perfil', 'middleware' => 'validado', 'namespace' => 'Perfil'], function(){

	Route::get('/try', 'WelcomeController@index');
	
});


Route::get('campeonatos',['uses'=>'CampeonatosController@index']);
Route::get('mis-campeonatos', ['middleware' => 'validado','uses'=>'CampeonatosController@mios']);
Route::get('campeonato/{id}/{nombre}',['uses'=>'CampeonatosController@show']);
Route::get('campeonato/{c_id}/{nombre}/resultados/',function($c_id,$nombre){
	return Redirect::to(url('campeonato/'.$c_id.'/'.$nombre));
});
Route::get('campeonato/{c_id}/{nombre}/resultados/{id}',['uses'=>'EventosController@show']);
Route::get('campeonato/{c_id}/{nombre}/subir-resultados/{id}',['uses'=>'EventosController@subir', 'middleware'=>'validado']);
Route::get('campeonato/{c_id}/{nombre}/agregar-evento',['uses'=>'EventosController@add', 'middleware'=>'validado']);


Route::get('circuitos/{id}/{nombre}',['uses'=>'CircuitosController@show']);
Route::get('circuitos',['uses'=>'CircuitosController@index']);
Route::get('circuitos/agregar',['uses'=>'CircuitosController@add', 'middleware'=>'validado']);



//POST
Route::post('circuitos/agregar',['uses'=>'CircuitosController@store', 'middleware'=>'validado']);
Route::post('eventos/agregar',['uses'=>'EventosController@store', 'middleware'=>'validado']);
Route::post('eventos/subir-log',['uses'=>'EventosController@storeLog', 'middleware'=>'validado']);

app/Campeonatos.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Eventos;
use App\PuntuacionCampeonatos;

class Campeonatos extends Model {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'campeonatos';


	/**
     * Función que devuelve el administrador
     *
     */
    public function administrador(){
        return $this->belongsTo('App\Usuarios');
    }

    /**
     * Función que devuelve el mod
     *
     */
    public function mod(){
        return $this->belongsTo('App\Mods');
    }

    /**
     * Función que devuelve los eventos
     *
     */
    public function eventos(){
        return $this->hasMany('App\Eventos')->orderBy('order');
    }

    /**
     * Función que devuelve las puntuaciones
     *
     */
    public function puntuacionCampeonatos(){
        return $this->hasMany('App\PuntuacionCampeonatos');
    }

    public static function puntosPosicion($posicion,$id) {
        $puntos= PuntuacionCampeonatos::where('campeonatos_id',$id)->where('posicion',$posicion)->first();
        if($puntos==null) {
            $puntosPosicion = 0;
        } else {
            $puntosPosicion = $puntos->puntos;
        }
        return $puntosPosicion;
    }

    public function getPosicionesCampeonatoAttribute(){
        $pilotos = [];
        $eventos = Eventos::where('campeonatos_id',$this->id)->where('completado',true)->get();
        if(count($eventos)>0) {
            $puntuaciones = $this->puntuacionCampeonatos()->get();
            
            foreach($eventos as $evento) {
                foreach($evento->resultados as $resultado){
                    //dd($resultado->pilotos()->first());
                    if(array_key_exists($resultado->pilotos()->first()->nombre, $pilotos)){
                        $pilotos[$resultado->pilotos()->first()->nombre]['puntos']+= self::puntosPosicion($resultado->posicion,$this->id);
                    } else {
                        $pilotos[$resultado->pilotos()->first()->nombre]= [
                            'nombre'        => $resultado->pilotos()->first()->nombre,
                            'escuderia'     => @$resultado->pilotos()->first()->pilotos_escuderias->nombre,
                            'puntos'        => $this->puntosPosicion($resultado->posicion,$this->id)
                            ];
                    }
                        
                }
            }
            //$pilotos['claudiosan']=['nombre'=>'Claudiosan','escuderia'=>'Escuderia','puntos'=>42];

            usort($pilotos,array("\App\Http\Controllers\Controller","ordenarPilotosPorPuntos"));
        }

        return $pilotos;

    }

}

app/Circuitos.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Paises;

class Circuitos extends Model {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'circuitos';


	/**
     * Función que devuelve el pais
     *
     */
    public function pais(){
        return $this->belongsTo('App\Paises');
    }

    public function getLocalizacionAttribute() {
        return Paises::where('pais',$this->pais)->first();
    }

    /**
     * Función que devuelve los eventos
     *
     */
    public function eventos(){
        return $this->hasMany('App\Eventos');
    }

}

app/Eventos.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Eventos extends Model {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'eventos';


	/**
     * Función que devuelve el campeonato
     *
     */
    public function campeonato(){
        return $this->belongsTo('App\Campeonatos');
    }

    /**
     * Función que devuelve el circuito
     *
     */
    public function circuito(){
        return $this->belongsTo('App\Circuitos');
    }

    public function getCircuitoAttribute(){
        return Circuitos::find($this->circuitos_id);
    }

    /**
     * Funcion que devuelve los resultados
     */
    public function resultados(){
    	return $this->hasMany('App\Resultados');
    }

}

app/Resultados.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Pilotos;
use App\Vueltas;
use App\Eventos;
use App\Campeonatos;

class Resultados extends Model {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'resultados';


	/**
     * Función que devuelve el evento
     *
     */
    public function evento(){
        return $this->belongsTo('App\Eventos');
    }

    /**
     * Función que devuelve el piloto
     *
     */
    public function pilotos(){
        return $this->belongsTo('App\Pilotos');
    }

    public function getPilotoAttribute(){
        return Pilotos::find($this->pilotos_id);
    }

    public function getTiempoCarreraAttribute(){
        $tiempo = $this->tiempo_total;
        $minutos = intval($tiempo/60);
        $resta_tiempo = $tiempo-($minutos*60);
        $resta_tiempo = explode(".", $resta_tiempo);
        return $minutos.":".sprintf("%02d.%03d",$resta_tiempo[0],@$resta_tiempo[1]);
    }

    public function getTiempoVueltaRapidaAttribute(){
        $vueltas = Vueltas::where('resultados_id',$this->id)->orderBy('tiempo_vuelta')->first();
        if(!$vueltas) {
            return "-:--.---";
        }
        $tiempo = $vueltas->tiempo_vuelta;
        $minutos = intval($tiempo/60);
        $resta_tiempo = $tiempo-($minutos*60);
        $resta_tiempo = explode(".", $resta_tiempo);
        return $minutos.":".sprintf("%02d.%03d",$resta_tiempo[0],@$resta_tiempo[1]);
    }

    public function getPuntosAttribute() {
        $evento = Eventos::find($this->eventos_id);
        $campeonato = Campeonatos::find($evento->campeonatos_id);
        return Campeonatos::puntosPosicion($this->posicion,$campeonato->id);
    }

    /**
     * Funcion que devuelve los vueltas
     */
    public function vueltas(){
    	return $this->hasMany('App\Vueltas');
    }

}

app/Http/Controllers/EventosController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Circuitos;
use App\Paises;
use App\Eventos;
use App\Campeonatos;
use App\Pilotos;
use App\Escuderias;
use App\PilotosEscuderias;
use App\Resultados;
use App\Vueltas;
use Validator;

use Illuminate\Http\Request;

class EventosController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

	public function storeLog(Request $request){
		//dd($request);
		$file = \Request::file('eventoLog');
		if ($file!== null){
			//dd($file);
			if($file->getClientMimeType()=='text/xml'){
				$evento = Eventos::find($request->evento_id);
				$path = '/log/'.$request->campeonato.'/'.$evento->id.'/'.$file->getClientOriginalName();
				\Storage::put($path,  \File::get($file));
				$evento->log = $path;
				$evento->completado = 1;
				$evento->save();

				//$xml = simplexml_load_file(storage_path().'/app'.$path);
				$content = utf8_encode(file_get_contents(storage_path().'/app'.$path));
				$xml = simplexml_load_string($content);
				//dd($xml);
				foreach($xml->RaceResults->Race->Driver as $driver) {
					$piloto = Pilotos::where('nombre', $driver->Name)->first();
					if(!$piloto) {
						//echo "no hay piloto";
						$piloto = new Pilotos;
						$piloto->nombre = $driver->Name;
						$piloto->save();
					}
					$escuderia = Escuderias::where('nombre', $driver->TeamName)->first();
					if(!$escuderia) {
						$escuderia = new Escuderias;
						$escuderia->nombre = $driver->TeamName;
						$escuderia->save();
					}

					$resultado = new Resultados;
					$resultado->eventos_id = $evento->id;
					$resultado->posicion = $driver->Position;
					$resultado->pilotos_id = $piloto->id;
					$resultado->tiempo_total = $driver->FinishTime;
					$resultado->total_vueltas = $driver->Laps;
					$resultado->total_boxes = $driver->Pitstops;
					$resultado->estado = $driver->FinishStatus;

					$resultado->save();
					//dd($driver->Lap);
					//dd($driver->Lap->attributes());
					foreach($driver->Lap as $lap) {
						$vuelta = new Vueltas;
						$vuelta->resultados_id = $resultado->id;
						$vuelta->vuelta = $lap->attributes()['num'];
						$vuelta->tiempo_vuelta = $lap;
						$vuelta->parcial_1 = $lap->attributes()['s1'];
						$vuelta->parcial_2 = $lap->attributes()['s2'];
						$vuelta->parcial_3 = $lap->attributes()['s3'];
						$vuelta->boxes = (@$lap->attributes()['pit']==1)?1:0;
						$vuelta->penalizacion =0;
						$vuelta->gasolina = $lap->attributes()['fuel'];
						$vuelta->posicion = $lap->attributes()['p'];

						$vuelta->save();
					}
					//dd($driver);
				}
			}
		}
		$champ = Campeonatos::find($request->campeonato);
		return \Redirect::to('/campeonato/'.$request->campeonato.'/'.str_slug($champ->nombre,'-'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		//dd($request);
		if($request->circuito==""){
			$rules= ['circuitoNombre'=>'required','paisCircuito'=>'required','distanciaCircuito'=>'required|integer'];
			$fields=['circuitoNombre','paisCircuito','distanciaCircuito'];
			$this->modelValidator($request,$rules,$fields);

			//$pais = Paises::where('pais',$request->paisCircuito)->first();

			$circuito = new Circuitos;
			$circuito->nombre = $request->circuitoNombre;
			$circuito->pais = $request->paisCircuito;
			$circuito->longitud = $request->distanciaCircuito;
			$circuito->imagen = $request->urlImagenCircuito;
			$circuito->descripcion = $request->descripcionCircuito;
			
			\Session::flash('message','Circuito grabado');
			$circuito->save();
			

		} else {
			$circuito = Circuitos::find($request->circuito);
		}

		$rules= ['eventoNombre'=>'required',
			'eventoFecha'=>'required',
			'eventoHoras'=>'required|integer',
			'eventoMinutos' => 'required|integer',
			'eventoDuracion' => 'required|integer'
			];
		$fields=['eventoNombre','eventoFecha','eventoHoras','eventoMinutos','eventoDuracion'];
		$this->modelValidator($request,$rules,$fields); 

		$champ = Campeonatos::find($request->campeonato);
		$order = count($champ->eventos);

		$evento = new Eventos;
		$evento->campeonatos_id = $champ->id;
		$evento->order = ++$order;
		$evento->circuitos_id = $circuito->id;
		$evento->nombre = $request->eventoNombre;
		$evento->descripcion = $request->eventoDescripcion;
		$evento->logo = $request->eventoLogo;
		$evento->imagen = "";//$request->
		$evento->fecha = $request->eventoFecha;
		$evento->hora = $request->eventoHoras.":".$request->eventoMinutos;
		$evento->tipo = $request->eventoTipo;
		$evento->duracion = $request->eventoDuracion;

		$evento->save();
		\Session::flash('message','Evento grabado');

		return \Redirect::to('/campeonato/'.$request->campeonato.'/'.str_slug($champ->nombre,'-'));
		
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($c_id,$nombre,$id)	{
		$campeonato = Campeonatos::find($id);
		if(!$campeonato) {
			return view('errors.404');
		}
		if(str_slug($campeonato->nombre)!=$nombre){
			return view('errors.404');
		}
		$evento = Eventos::find($id);
		$resultados = Resultados::where('eventos_id',$id)->orderBy('posicion')->get();
		return view('eventos.mostrar')->with(['campeonato'=>$campeonato,'posiciones'=>0,'evento'=>$evento,'resultados'=>$resultados]);
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

	public function add($c_id,$nombre){
		$circuitos = Circuitos::all();
		$paises = Paises::all();

		return view('eventos.agregar')->with(['circuitos'=>$circuitos,'paises'=>$paises,'campeonato'=>$c_id]);
	}

	public function subir($c_id,$nombre,$id){
		$evento = Eventos::find($id);
		return view('eventos.subir-resultados')->with(['evento'=>$evento,'nombre'=>$nombre,'campeonato'=>$c_id]);
	}

}

resources/views/eventos/agregar.blade.php
@extends('base')

@section('header')
	<link href='/js/chosen/chosen.css' rel='stylesheet' type='text/css'>
	<script type="text/javascript" src="/js/chosen/chosen.jquery.min.js"></script>
	
	<script type="text/javascript" src="/js/jquery.validate.js"></script>

@endsection

@section('scripts')
<script>
	jQuery(".select-circuito").chosen({no_results_text: "Oops, no se ha encontrado nada!",allow_single_deselect: true}); 
	 

	jQuery( "#eventoFecha" ).datepicker({altFormat: "yy-mm-dd",dateFormat: "yy-mm-dd"});

	function agregarCircuito(){
		jQuery('#id-circuito').removeClass('required');
		jQuery('.crear-circuito').removeClass('hidden');

		jQuery('#circuitoNombre').addClass('required');
		jQuery('#paisCircuito').addClass('required');
		jQuery(".select-pais-circuito").chosen({no_results_text: "Oops, el pais no se encuentra!",allow_single_deselect: true});

	}
	jQuery(document).ready(function(){ $("#formEventos").validate(); }); 
</script>
@endsection

@section('content')

<div class="section">
	  <div class="container">
		<div class="row">
		  <div class="col-md-12">
			<div class="page-header">
			  <h1>Agregar Evento </h1>
			</div>
		  </div>
		</div>
	  </div>
	</div>
	<div class="section">
		<form role="form" method="POST" id="formEventos" action="{{ action('EventosController@store')}}">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		<input type="hidden" name="campeonato" value="{{ $campeonato }}">
	  <div class="container">
		<div class="row">
		  <div class="col-md-12">
			<div class="col-md-4">

				<div class="form-group">
				  <label class="control-label" for="circuito">Circuito</label><br />
				  <select data-placeholder="Selecciona el circuito" name="circuito" id="id-circuito" class="form-control select-circuito required" >
						<option></option>
						@foreach($circuitos as $circuito)
							<option value="{{$circuito->id}}">{{$circuito->nombre}}</option>
						@endforeach
				  </select>
				  
				</div>
				<a class="btn btn-primary" id="btn-agregar-circuito" href="javascript:agregarCircuito();">Agregar Circuito</a>
				<!--<a class="btn btn-primary hidden" id="btn-cerrar-agregar-circuito" href="javascript:agregarCircuito();">Seleccionar</a>-->

				<div class="crear-circuito hidden">
				<br /><br />
					<div class="form-group">
						<label class="control-label" for="circuitoNombre">Nombre del circuito</label>
						<input class="form-control" id="circuitoNombre" name="circuitoNombre" placeholder="Nombre del circuito" type="text">
					</div>
					<div class="form-group">
						<label class="control-label" for="paisCircuito">Pais del circuito</label>
						<select data-placeholder="Selecciona el pais" name="paisCircuito" id='paisCircuito' class="form-control select-pais-circuito" >
							<option></option>
							@foreach($paises as $pais)
								<option value="{{$pais->pais}}">{{$pais->name}}</option>
							@endforeach
						</select>
					</div>

					<div class="form-group">
						<label class="control-label" for="distanciaCircuito">Distancia/Longitud del circuito</label>
						<input class="form-control" id="distanciaCircuito" name="distanciaCircuito" placeholder="metros" type="text">
					</div>
					<div class="form-group">
						<label class="control-label" for="urlImagenCircuito">URL a la imagen del circuito</label>
						<input class="form-control" id="urlImagenCircuito" name="urlImagenCircuito" placeholder="http://" type="text">
					</div>
					<div class="form-group">
						<label class="control-label" for="descripcionCircuito">Descripcion del circuito</label>
						<textarea class="form-control" name="descripcionCircuito" rows=""></textarea>
					</div>
				</div>


			</div>
			<div class="col-md-1"></div>
			<div class="col-md-7">
				<div class="form-group">
				  <label class="control-label" for="eventoNombre">Nombre*</label>
				  <input class="form-control required" id="eventoNombre" name="eventoNombre" placeholder="Nombre del evento" type="text">
				</div>
				<div class="form-group">
				  <label class="control-label" for="eventoDescripcion">Descripcion</label>
				  <input class="form-control" id="eventoDescripcion" name="eventoDescripcion" placeholder="Descripcion" type="text">
				</div>
				<div class="form-group">
				  <label class="control-label" for="eventoLogo">Logo image</label>
				  <input class="form-control" id="eventoLogo" name="eventoLogo" placeholder="http://" type="text">
				</div>
				<div class="form-group">
				  <label class="control-label" for="eventoNombre">Fecha y Hora*</label>
				  <div class="row">
						<div class="col-xs-6">
							<input class="form-control required" id="eventoFecha" name="eventoFecha" placeholder="{{date('Y-m-d')}}" type="text">
						</div>
						<div class="col-xs-6">
							<div class="row">
								<div class="col-xs-6">
									<select data-placeholder="Horas" name="eventoHoras" id='eventoHoras' class="form-control select-evento-horas required" >
										<option value="">Horas</option>
										@for($i=0;$i<24;$i++)
											<option value="{{$i}}">{{sprintf('%02d',$i)}}</option>
										@endfor
									</select>
								</div>
								<div class="col-xs-6">
									<select data-placeholder="Minutos" name="eventoMinutos" id='eventoMinutos' class="form-control select-evento-minutos required" >
										<option value="">Minutos</option>
										@for($i=0;$i<60;$i+=5)
											<option value="{{$i}}">{{sprintf('%02d',$i)}}</option>
										@endfor
									</select>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="form-group">
					<label class="control-label" for="eventoTipo">Duracion *</label>
					<div class="row">
						<div class="col-xs-6">
							<select data-placeholder="Tipo de ducacion" name="eventoTipo" id='eventoTipo' class="form-control select-pais-duracion" >
								<option value="vueltas">Vueltas</option>
								<option value="tiempo">Tiempo</option>
							</select>
						</div>
						<div class="col-xs-6">
							<input class="form-control required" id="eventoDuracion" name="eventoDuracion" placeholder="Cantidad" type="number">
						</div>
					</div>
				</div>
				<button class="btn btn-lg btn-primary btn-block" type="submit">Grabar</button>

			</div>
		  </div>
		</div>
	  </div>
	  </form>
	</div>

@endsection

resources/views/eventos/mostrar.blade.php
@extends('base')

@section('content')
	<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="page-header">
              <h1>{{$campeonato->nombre}}
                <small>{{$campeonato->descripcion}}</small>
              </h1>

              <h1>Resultados Carrera
                <small>{{$evento->fecha}}</small>
              </h1>
            </div>
          </div>
        </div>
        
    </div>
	<div class="section">
	  <div class="container">
		<div class="row">
		  <div class="col-md-4">
			<ul class="media-list">
				
				  <li class="media detalle">
					<a class="pull-left" href="#">
						@if($evento->imagen!="")
							<img class="media-object" src="{{$evento->imagen}}" height="64" width="64">
						@elseif($evento->logo!="")
							<img class="media-object" src="{{$evento->logo}}" height="64" width="64">
						@elseif($evento->circuito->imagen!="")
							<img class="media-object" src="{{$evento->circuito->imagen}}" height="64" width="64">
						@else
							<img class="media-object" src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" height="64" width="64">
						@endif
					</a>
					<div class="media-body">

					  <h4 class="media-heading">{{$evento->nombre}}</h4>
					  <small>{{$evento->descripcion}}</small>
					  <p><img src="{{$evento->circuito->localizacion->bandera}}" width="20" /> <a href='{{ action('CircuitosController@show',['id'=>$evento->circuito->id,'nombre'=>str_slug($evento->circuito->nombre,'-') ]) }}'>{{$evento->circuito->nombre }}</a></p>
					  
					</div>
				  </li>
			  	
				{{--
			  	@if(!\Auth::guest() && \Auth::user()->id== $campeonato->administrador) 
			  		<li class="media detalle">
					<a class="pull-left" href="#">
						<img class="media-object" src="http://pingendo.github.io/pingendo-bootstrap/assets/placeholder.png" height="64" width="64">
					</a>
					<div class="media-body">

					  <h4 class="media-heading">Agrega un evento</h4>
					  <small></small>
					  
					  	<p><a href="{{ action('EventosController@add',['c_id'=>$campeonato->id,'nombre'=>str_slug($campeonato->nombre,'-')] ) }}">Agregar</a></p>
					</div>
				  </li>
			  	@endif
			  	--}}
			</ul>
		  </div>
		  <div class="col-md-1"></div>
		  <div class="col-md-7">
			<table class="table">
			  <thead>
				<tr>
				  <th>#</th>
				  <th>Piloto</th>
				  <th>Tiempo</th>
				  <th>Mejor Tiempo</th>
				  <th>Vueltas</th>
				  <th>Puntos</th>
				</tr>
			  </thead>
			  {{--dd($campeonato->devolverPosicionesCampeonato())--}}
				{{--dd(($campeonato->posiciones_campeonato))--}}
			  <tbody>
			  	@if(count($resultados)>0)
			  		@foreach($resultados as $posicion)
						<tr>
						  <td>{{++$posiciones}}</td>
						  <td>{{$posicion->piloto->nombre}}</td>
						  <td>{{$posicion->tiempo_carrera}}</td>
						  <td>{{$posicion->tiempo_vuelta_rapida}}</td>
						  <td>{{$posicion->total_vueltas}}</td>
						  <td>{{$posicion->puntos}}</td>
						</tr>
					@endforeach
				@endif
				
			  </tbody>
			</table>
		  </div>
		</div>
	  </div>
	</div>

@endsection

resources/views/eventos/subir-resultados.blade.php
@extends('base')

@section('header')
	<link href='/js/chosen/chosen.css' rel='stylesheet' type='text/css'>
	<script type="text/javascript" src="/js/chosen/chosen.jquery.min.js"></script>
	
	<script type="text/javascript" src="/js/jquery.validate.js"></script>

@endsection

@section('scripts')
<script>
	jQuery(".select-circuito").chosen({no_results_text: "Oops, no se ha encontrado nada!",allow_single_deselect: true}); 
	 

	jQuery( "#eventoFecha" ).datepicker({altFormat: "yy-mm-dd",dateFormat: "yy-mm-dd"});

	function agregarCircuito(){
		jQuery('#id-circuito').removeClass('required');
		jQuery('.crear-circuito').removeClass('hidden');

		jQuery('#circuitoNombre').addClass('required');
		jQuery('#paisCircuito').addClass('required');
		jQuery(".select-pais-circuito").chosen({no_results_text: "Oops, el pais no se encuentra!",allow_single_deselect: true});

	}
	jQuery(document).ready(function(){ $("#formEventos").validate(); }); 
</script>
@endsection

@section('content')

<div class="section">
	  <div class="container">
		<div class="row">
		  <div class="col-md-12">
			<div class="page-header">
			  <h1>Subir Resultados Evento </h1>
			  {{$evento->nombre}} - {{$evento->circuito->nombre}} <br />
			  {{$evento->fecha}} {{$evento->hora}}
			</div>
		  </div>
		</div>
	  </div>
	</div>
	<div class="section">
		<form role="form" method="POST" id="formEventos" action="{{ action('EventosController@storeLog')}}" enctype="multipart/form-data">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">
		<input type="hidden" name="campeonato" value="{{ $campeonato }}">
		<input type="hidden" name="evento_id" value="{{ $evento->id }}">
	  <div class="container">
		<div class="row">
		  <div class="col-md-12">
			
			<div class="col-md-7">
				<div class="form-group">
				  <label class="control-label" for="eventoLog">Subir Log*</label>
				  <input accept="*.xml" class="form-control required" id="eventoLog" name="eventoLog" placeholder="Log de resultados" type="file">


				</div>
				
				<button class="btn btn-lg btn-primary btn-block" type="submit">Grabar</button>

			</div>
		  </div>
		</div>
	  </div>
	  </form>
	</div>

@endsection